<?php
@session_start();
include_once("../../../config/conneect.php");
include_once('OAuth.php');

//pesapal params
$token=$params=NULL;


 $paygateway = new PayGateway(null);
        $paypalInfo = $paygateway->getPesapal();
     
        if ($paypalInfo->isTestMode() == 1) {
            $actionUrl = "http://demo.pesapal.com/";
        } else {
            $actionUrl = "https://pesapal.com/";
        }
        
/*
PesaPal Sandbox is at http://demo.pesapal.com. Use this to test your developement and 
when you are ready to go live change to https://www.pesapal.com.
*/
$consumer_key = $paypalInfo->getBusinessId();//Register a merchant account on
                   //demo.pesapal.com and use the merchant key for testing.
                   //When you are ready to go live make sure you change the key to the live account
                   //registered on www.pesapal.com!
$consumer_secret = $paypalInfo->getToken();// Use the secret from your test
                   //account on demo.pesapal.com. When you are ready to go live make sure you 
                   //change the secret to the live account registered on www.pesapal.com!
$signature_method = new OAuthSignatureMethod_HMAC_SHA1();
$iframelink = $actionUrl . 'api/PostPesapalDirectOrderV4';//change to      
                   //https://www.pesapal.com/API/PostPesapalDirectOrderV4 when you are ready to go live!

                   
                   
//get form details
$amount = $amount;
$amount = number_format($amount, 2);//format amount to 2 decimal places

$desc = $itemdescription;
$type = 'MERCHANT'; //default value = MERCHANT
$reference = $invoice_id;//unique order id of the transaction, generated by merchant

$user = db_fetch_array(db_query("select * from registration where id = '$_SESSION[userid]'"));

$first_name = $user['firstname'];
$last_name = $user['lastname'];
$email = 'esokolive@gmail.com';
$phonenumber = '';//ONE of email or phonenumber is required

$callback_url = 'http://' . $_SERVER['SERVER_NAME'] . '/payment_success.php'; //redirect url, the page that will handle the response from pesapal.

$post_xml = "<?xml version=\"1.0\" encoding=\"utf-8\"?><PesapalDirectOrderInfo xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" Amount=\"".$amount."\" Description=\"".$desc."\" Type=\"".$type."\" Reference=\"".$reference."\" FirstName=\"".$first_name."\" LastName=\"".$last_name."\" Email=\"".$email."\" PhoneNumber=\"6032620569\" xmlns=\"http://www.pesapal.com\"/>";
$post_xml = htmlentities($post_xml);

$consumer = new OAuthConsumer($consumer_key, $consumer_secret, $callback_url);

//post transaction to pesapal
$iframe_src = OAuthRequest::from_consumer_and_token($consumer, $token, "GET", $iframelink, $params);
$iframe_src->set_parameter("oauth_callback", $callback_url);
$iframe_src->set_parameter("pesapal_request_data", $post_xml);


$iframe_src->sign_request($signature_method, $consumer, $token);

//display pesapal - iframe and pass iframe_src
//header("location: $iframe_src");
?>
<iframe src="<?php echo $iframe_src;?>" width="100%" height="620px"  scrolling="no" frameBorder="0">
	<p>Browser unable to load iFrame</p>
</iframe>
